# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "html5forms-rails"
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kristian Mandrup"]
  s.date = "2012-08-27"
  s.description = "Use the power of html5 forms even in old browsers using polyfills :)"
  s.email = "kmandrup@gmail.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "CHANGELOG.md",
    "Gemfile",
    "README.md",
    "Rakefile",
    "VERSION",
    "html5forms-rails.gemspec",
    "lib/html5forms.rb",
    "vendor/assets/images/h5f/form_validation.png",
    "vendor/assets/images/html5form-shim/asterisk.png",
    "vendor/assets/images/html5form-shim/down.png",
    "vendor/assets/images/html5form-shim/fail.png",
    "vendor/assets/images/html5form-shim/ok.png",
    "vendor/assets/images/html5forms/jscolor/arrow.gif",
    "vendor/assets/images/html5forms/jscolor/cross.gif",
    "vendor/assets/images/html5forms/jscolor/hs.png",
    "vendor/assets/images/html5forms/jscolor/hv.png",
    "vendor/assets/images/html5forms/slider/slider-1.png",
    "vendor/assets/images/html5forms/slider/slider-disabled-1.png",
    "vendor/assets/images/html5forms/slider/slider-disabled.png",
    "vendor/assets/images/html5forms/slider/slider.png",
    "vendor/assets/javascripts/h5f.js",
    "vendor/assets/javascripts/h5f.min.js",
    "vendor/assets/javascripts/html5forms/EventHelpers.min.js",
    "vendor/assets/javascripts/html5forms/autocomplete.min.js",
    "vendor/assets/javascripts/html5forms/cssQuery-p.min.js",
    "vendor/assets/javascripts/html5forms/dev/EventHelpers.js",
    "vendor/assets/javascripts/html5forms/dev/autocomplete.js",
    "vendor/assets/javascripts/html5forms/dev/cssQuery-p.js",
    "vendor/assets/javascripts/html5forms/dev/html5.js",
    "vendor/assets/javascripts/html5forms/dev/html5Forms.js",
    "vendor/assets/javascripts/html5forms/dev/html5Widgets.js",
    "vendor/assets/javascripts/html5forms/dev/jscolor.js",
    "vendor/assets/javascripts/html5forms/dev/slider.js",
    "vendor/assets/javascripts/html5forms/dev/timer.js",
    "vendor/assets/javascripts/html5forms/dev/visibleIf.js",
    "vendor/assets/javascripts/html5forms/html5.min.js",
    "vendor/assets/javascripts/html5forms/html5Forms.min.js",
    "vendor/assets/javascripts/html5forms/html5Widgets.min.js",
    "vendor/assets/javascripts/html5forms/jscolor.min.js",
    "vendor/assets/javascripts/html5forms/slider.min.js",
    "vendor/assets/javascripts/html5forms/timer.min.js",
    "vendor/assets/javascripts/html5forms/visibleIf.min.js",
    "vendor/assets/javascripts/jquery.html5form-shim.js",
    "vendor/assets/javascripts/jquery.html5form.min.js",
    "vendor/assets/stylesheets/h5f.css",
    "vendor/assets/stylesheets/html5form-shim.css",
    "vendor/assets/stylesheets/html5forms/number.css",
    "vendor/assets/stylesheets/html5forms/slider.css",
    "vendor/assets/stylesheets/html5forms/slider_ie.css",
    "vendor/assets/stylesheets/html5forms/useragentmanExample.css",
    "vendor/assets/stylesheets/html5forms/visibleIf.css"
  ]
  s.homepage = "http://github.com/kristianmandrup/jqtools-rails"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "HTML5forms packages for Rails asset pipeline"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_development_dependency(%q<rdoc>, [">= 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_development_dependency(%q<simplecov>, [">= 0.5"])
    else
      s.add_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_dependency(%q<rdoc>, [">= 3.12"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_dependency(%q<simplecov>, [">= 0.5"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.8.0"])
    s.add_dependency(%q<rdoc>, [">= 3.12"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, [">= 1.8.3"])
    s.add_dependency(%q<simplecov>, [">= 0.5"])
  end
end

